<?php

namespace k1lib\oexec;

const OEXEC_PHASE_NONE = 0;
const OEXEC_PHASE_CONSTRUCTION = 1;
const OEXEC_PHASE_CONFIG = 2;
const OEXEC_PHASE_LAUNCHING = 3;
const OEXEC_PHASE_EXECUTING = 4;
const OEXEC_PHASE_END = 5;

